// lessons.js
const allLessons = {
    
        "第 5 課：¿Dónde está la estación? (車站在哪裡？)": [
            { ch: "不好意思，普拉多博物館在哪裡？", sp: "Perdona, ¿dónde está el museo del Prado?" },
            { ch: "離這裡有一點遠。你得搭地鐵。", sp: "Está un poco lejos de aquí. Tienes que coger el metro." },
            { ch: "地鐵站在哪裡？離這裡很近。就在書報攤對面。", sp: "¿Dónde está la estación de metro? Está cerca de aquí. Está enfrente del quiosco." },
            { ch: "非常感謝。 / 不客氣。", sp: "Muchas gracias. De nada." },
            { ch: "嗨，安東尼奧。真巧。你住在這附近嗎？", sp: "Hola, Antonio. Qué casualidad. ¿Vives cerca de aquí?" },
            { ch: "不，我在這裡是因為我和女朋友有約。", sp: "No, estoy aquí porque tengo una cita con mi novia." },
            { ch: "你現在住在哪裡？我住在合租公寓。公寓在索里亞街。", sp: "¿Dónde vives ahora? Vivo en un piso compartido. El piso está en la calle Zorrilla." },
            { ch: "我筋疲力竭，因為我有很多工作。", sp: "Estoy agotado porque tengo mucho trabajo." },
            { ch: "你來自哪裡？我來自馬德里。", sp: "¿De dónde eres tú? Yo soy de Madrid." },
            { ch: "你住在哪裡？我和朋友住在一間公寓裡。", sp: "¿Dónde vives? Vivo en un piso con mi amigo." },
            { ch: "公寓在哪裡？公寓在一家麵包店對面。", sp: "¿Dónde está el piso? El piso está enfrente de una panadería." },
            { ch: "麵包店在哪裡？它在教堂前面，廣場後面。", sp: "¿Dónde está la panadería? Está delante de la iglesia y detrás de la plaza." },
            { ch: "公寓在報攤旁邊嗎？公寓就在那裡。", sp: "¿Está el piso al lado de un quiosco? Allí está el piso." },
            { ch: "Elisa，妳丈夫在哪裡？他在法國出差。", sp: "Elisa, ¿dónde está tu marido? Está de viaje de negocios por Francia." },
            { ch: "明天他在巴黎有一個會議。", sp: "Mañana tiene una reunión en París." },
            { ch: "你們現在住在馬德里嗎？不，我們在薩拉曼卡買了一棟別墅。", sp: "¿Vivís en Madrid ahora? No, mi marido y yo compramos un chalé en Salamanca." },
            { ch: "離市中心有點遠，但在一個非常安靜的區域。", sp: "Está un poco lejos del centro, pero está en una zona muy tranquila." },
            { ch: "手機在哪裡？手機在桌子上。", sp: "¿Dónde está el móvil? El móvil está encima de la mesa." },
            { ch: "你父親在哪裡工作？我父親在一所學校工作。", sp: "¿Dónde trabaja tu padre? Mi padre trabaja en una escuela." }
        ],
        "第 6 課：Hay comedor en la facultad (學院裡有食堂)": [
            { ch: "你知道圖書館在哪裡嗎？就在影印店旁邊。", sp: "¿Sabes dónde está la biblioteca? Está ahí, al lado de la tienda de fotocopias." },
            { ch: "學院裡有食堂或咖啡廳嗎？", sp: "¿Hay un comedor o una cafetería en la facultad?" },
            { ch: "是的，這一層有一間咖啡廳和一個食堂。", sp: "Sí, hay una cafetería y un comedor en esta planta." },
            { ch: "一樓有什麼？有一些教室，秘書處也在那裡。", sp: "¿Qué hay en la primera planta? Hay unas aulas y la Secretaría está allí también." },
            { ch: "我明白了。非常感謝。", sp: "Ya veo. Muchas gracias." },
            { ch: "學院裡有多少間教室？有 10 間教室。", sp: "¿Cuántas aulas hay en la academia? Hay diez aulas en la academia." },
            { ch: "學院裡有多少學生？大約有 75 名學生。", sp: "Hay unos setenta y cinco alumnos en nuestra academia." },
            { ch: "哥雅街有一間咖啡廳。在超市旁邊。", sp: "Hay una cafetería en la calle Goya. La cafetería está al lado del supermercado." },
            { ch: "巴勃羅是一位親切的老師。", sp: "Pablo es un profesor amable." },
            { ch: "我班上大約有 30 名學生。", sp: "Hay unos treinta estudiantes in my clase." },
            { ch: "西班牙人很親切。", sp: "Los españoles son amables." },
            { ch: "狗在這裡。貓在那裡。背包在那裡（遠處）。", sp: "El perro está aquí. El gato está ahí. La mochila está allí." },
            { ch: "教室在哪裡？在走廊盡頭。", sp: "¿Dónde está el aula? Está al final del pasillo." },
            { ch: "教室裡有一塊黑板和一些桌子。有投影機嗎？", sp: "Hay una pizarra y unas mesas en el aula. ¿Hay un proyector allí?" },
            { ch: "不，沒有投影機。", sp: "No, no hay proyector." },
            { ch: "你現在住在哪裡？我住在附近的一間公寓。", sp: "¿Dónde vives ahora? Vivo en un piso por aquí cerca." },
            { ch: "我有兩個室友。我住在二樓（西班牙一樓）。", sp: "Tengo dos compañeras de piso. Vivo en la primera planta." },
            { ch: "是一間附家具的公寓嗎？是的。", sp: "¿Es un piso amueblado? Sí." }
        ],
        "第 7 課：Ellos son mis padres (他們是我的父母)": [
            { ch: "年長的是我的祖父母。他們是誰？", sp: "Los mayores son mis abuelos. ¿Quiénes son?" },
            { ch: "他們是我的父母，那邊那些是我的叔伯舅姨。", sp: "Ellos son mis padres y aquellos son mis tíos." },
            { ch: "你有兄弟姊妹嗎？有。這是我的哥哥，這是我的妹妹。", sp: "¿Tienes hermanos? Sí. Este es mi hermano mayor y esta es mi hermana menor." },
            { ch: "你好，Ana。這位是 David，我的丈夫。", sp: "Hola, Ana. Este es David, mi marido." },
            { ch: "那個男孩是妳兒子，他很高。是的，他叫 Miguel，五歲，很調皮。", sp: "Aquel chico es tu hijo. Es muy alto. Sí, se llama Miguel. Tiene cinco años y es travieso." },
            { ch: "David今年四歲和妳兒子一樣調皮。但 David 比 Miguel 矮。", sp: "David tiene cuatro años y es tan travieso como tu hijo. Pero David es más bajo que Miguel." },
            { ch: "那邊那些男孩是我的同事。那個女孩是我妹妹。", sp: "Aquellos chicos son mis compañeros. Esa chica es mi hermana menor." },
            { ch: "這是我兄弟。這是我姊妹。", sp: "Este es mi hermano. Esta es mi hermana." },
            { ch: "Felisa 比 Elisa 漂亮。José 沒有 Enrique 那麼帥。", sp: "Felisa es más guapa que Elisa. José es menos guapo que Enrique." },
            { ch: "Luisa 和 Lucía 一樣漂亮。", sp: "Luisa es tan guapa como Lucía." },
            { ch: "Felisa 說話比 Elisa 多。José 吃得比 Enrique 少。", sp: "Felisa habla más que Elisa. José come menos que Enrique." },
            { ch: "我擁有的書比 Pedro 一樣多。", sp: "Yo tengo tantos libros como Pedro." },
            { ch: "Antonio 比我大。我比 Antonio 小。", sp: "Antonio es mayor que yo. Yo soy menor que Antonio." },
            { ch: "這幅畫比那幅好。這本書比那本差。", sp: "Este cuadro es mejor que aquel. Este libro es peor que aquel." },
            { ch: "那個高個子男人是誰？是我堂兄弟。在他右邊的是我叔叔。", sp: "¿Quién es el hombre alto? Es mi primo. A la derecha de mi primo es mi tío." },
            { ch: "那些女人是誰？", sp: "¿Quiénes son las mujeres?" },
            { ch: "那位年長的女性是我嬸嬸。她在我的堂姊妹左邊。", sp: "La mujer mayor es mi tía. Está a la izquierda de mi prima." },
            { ch: "你有幾個兄弟姊妹？", sp: "¿Cuántos hermanos tienes?" },
            { ch: "你哥哥結婚了嗎？是的，他結婚了，有一個兒子。他們住在這附近。", sp: "¿Está casado tu hermano mayor? Sí, está casado y tiene un hijo. Viven cerca de aquí." },
            { ch: "那妳妹妹呢？她單身，但有男朋友。", sp: "¿Y tu hermana menor? Está soltera, pero tiene novio." }
        ],
        "第 8 課：¿Sabes cómo llegar allí? (你知道怎麼去那裡嗎？)": [
    { "ch": "我們這週末去拉阿貝卡如何？", "sp": "¿Qué tal si vamos a La Alberca este fin de semana?" },
    { "ch": "那是附近的一個城鎮。", "sp": "Es un pueblo cercano." },
    { "ch": "好主意！", "sp": "¡Buena idea!" },
    { "ch": "你知道如何到那裡嗎？", "sp": "¿Sabes cómo llegar allí?" },
    { "ch": "還有我們要住哪裡？", "sp": "¿Y dónde nos alojamos?" },
    { "ch": "我不太熟悉那個鄉鎮，不過我們可以上網搜尋。", "sp": "No conozco muy bien ese pueblo, pero podemos buscar por internet." },
    { "ch": "那你知道我們可以在哪裡租車嗎？", "sp": "¿Sabes dónde podemos alquilar un coche?" },
    { "ch": "嗯，我知道這附近的一家租車行。", "sp": "Sí, conozco un alquiler de coches cerca de aquí." },
    { "ch": "妳認識那個女人嗎？", "sp": "¿Conoces a esa mujer?" },
    { "ch": "認識，她是艾蜜莉亞，安立奎的女朋友。", "sp": "Sí, es Emilia, la novia de Enrique." },
    { "ch": "她來自哪裡？", "sp": "¿De dónde es?" },
    { "ch": "她是台灣人，但西班牙語和法語程度很好。", "sp": "Es taiwanesa, pero sabe muy bien español y francés." },
    { "ch": "安立奎和她是同事。", "sp": "Enrique y ella son compañeros de oficina." },
    { "ch": "我們在公園散步怎麼樣？", "sp": "¿Qué tal si paseamos por el parque?" },
    { "ch": "你知道安立奎有個女兒嗎？", "sp": "¿Sabes que Enrique tiene una hija?" },
    { "ch": "我不知道安立奎有個女兒。", "sp": "No sé que Enrique tiene una hija." },
    { "ch": "我不知道車站在哪裡。", "sp": "No sé dónde está la estación." },
    { "ch": "你知道怎麼用這部相機嗎？", "sp": "¿Sabes cómo usar la cámara?" },
    { "ch": "很抱歉，我不知道。", "sp": "Lo siento, no lo sé." },
    { "ch": "艾莉西亞西班牙語（能力）很好。", "sp": "Alicia sabe muy well español." },
    { "ch": "愛麗莎完全不會／不懂西班牙語。", "sp": "Elisa no sabe nada de español." },
    { "ch": "瑪莉亞很熟台南。", "sp": "María conoce muy bien Tainan." },
    { "ch": "你認識艾蜜莉亞嗎？", "sp": "¿Conoces a Emilia?" },
    { "ch": "因為我感冒了，所以不能唱歌。", "sp": "No puedo cantar porque estoy resfriado." },
    { "ch": "你可以（到）機場接我嗎？", "sp": "¿Puedes recogerme en el aeropuerto?" },
    { "ch": "我的兄弟會踢足球。", "sp": "Mi hermano sabe jugar al fútbol." },
    { "ch": "我要去馬德里。", "sp": "Voy a Madrid." },
    { "ch": "我要去參加他的生日派對。", "sp": "Voy a la fiesta de su cumpleaños." },
    { "ch": "我會買一本字典。", "sp": "Voy a comprar un diccionario." },
    { "ch": "胡安娜這個週末會開派對。", "sp": "Juana va a hacer una fiesta este fin de semana." },
    { "ch": "去購物", "sp": "ir de compras" },
    { "ch": "去旅行", "sp": "ir de viaje" },
    { "ch": "去小酌", "sp": "ir de tapas" },
    { "ch": "大衛刮自己的鬍子。", "sp": "David se afeita." },
    { "ch": "安娜和艾蜜莉亞認識彼此。", "sp": "Ana y Emilia se conocen." },
    { "ch": "你熟悉這個城鎮嗎？", "sp": "¿Conoces bien este pueblo?" },
    { "ch": "一點點。為什麼（問）？", "sp": "Un poco. ¿Por qué?" },
    { "ch": "你知道我可以在哪裡野餐嗎？", "sp": "¿Sabes dónde puedo hacer pícnic?" },
    { "ch": "我知道這附近的一座公園。你可以在那裡野餐。", "sp": "Conozco un parke cerca de aquí. Puedes hacer pícnic allí." },
    { "ch": "那我可以在哪裡喝咖啡呢？", "sp": "¿Y dónde puedo tomar café?" },
    { "ch": "我不知道(這件事)，但我們可以在網路上搜尋。", "sp": "No lo sé, pero podemos buscar por internet." },
    { "ch": "我們和愛娃還有安立奎一起去露營如何？", "sp": "¿Qué tal si vamos de camping con Eva y Enrique?" },
    { "ch": "好主意！我們可以在那裡烤肉，還有做海鮮飯。", "sp": "¡Buena idea! Podemos hacer barbacoa y paella allí." },
    { "ch": "但是，你知道怎麼做海鮮飯嗎？", "sp": "Pero, ¿Sabes cómo hacer paella?" },
    { "ch": "當然。而且，我還會做水果酒和小菜。", "sp": "Por supuesto. Además, voy a hacer sangría y tapas." },
      ],

    "第 9 課：奶奶的生日與公司派對": [
    // 主題對話
    { "ch": "他幾歲？", "sp": "¿Cuántos años tiene?" },
    { "ch": "這個星期日我們一起喝個咖啡，你覺得如何？", "sp": "¿Qué te parece si tomamos un café juntos este domingo?" },
    { "ch": "這個星期日我們要慶慶祝奶奶的生日。", "sp": "Este domingo celebramos el cumpleaños de mi abuela." },
    { "ch": "真好！她（今年）滿幾歲？", "sp": "¡Qué bien! ¿Cuántos años cumple?" },
    { "ch": "(今年) 她要滿 70 歲了。", "sp": "Cumple setenta años." },
    { "ch": "她年紀大了，但她（還是）很常跟我爺爺一起旅行。", "sp": "Es mayor, pero viaja mucho con mi abuelo." },
    { "ch": "你的爺爺幾歲？", "sp": "¿Cuántos años tiene tu abuelo?" },
    { "ch": "他 72 歲。", "sp": "Tiene setenta y dos años." },
    { "ch": "明天是我公司五週年。", "sp": "Mañana es el quinto aniversario de mi empresa." },
    { "ch": "我們（明天）要辦一場派對。", "sp": "Vamos a hacer una fiesta." },
    { "ch": "恭喜！你們在哪裡辦派對？", "sp": "¡Felicidades! ¿Dónde hacéis la fiesta?" },
    { "ch": "在「Gustísimo」義式餐廳。", "sp": "En el restaurante italiano Gustísimo." },
    { "ch": "餐廳在 Melissa 飯店四樓。", "sp": "Está en el tercer piso del Hotel Melissa." },
    { "ch": "多少人會去參加派對？", "sp": "¿Cuántas personas van a la fiesta?" },
    { "ch": "超過 50 人。", "sp": "Más de cincuenta." },
    { "ch": "如果你想要的話，可以跟我一起來。", "sp": "Puedes venir conmigo si quieres." },

    // 進階日常對話：餐廳訂位
    { "ch": "你好！我想要訂位。", "sp": "¡Hola! Quiero reservar una mesa." },
    { "ch": "您想要幾個人的位子？", "sp": "¿Para cuántas personas?" },
    { "ch": "五個人。", "sp": "Para cinco personas." },
    { "ch": "（用餐時間）什麼時候？", "sp": "¿Para cuándo?" },
    { "ch": "明天晚上。", "sp": "Para mañana por la noche." },
    { "ch": "好的。麻煩（給我）您的姓、名及手機電話號碼。", "sp": "Muy bien. Su apellido y nombre, el número de teléfono móvil, por favor." },
    { "ch": "路卡斯．戈梅斯。我的號碼是 693 33 22 10。", "sp": "Lucas Gómez. Mi número es el seiscientos noventa y tres trescientos treinta y dos doscientos diez." },

    // 年齡與家庭狀況詢問
    { "ch": "你幾歲？", "sp": "¿Cuántos años tienes?" },
    { "ch": "我 31 歲。", "sp": "Tengo treinta y un años." },
    { "ch": "你（這次生日）滿幾歲？", "sp": "¿Cuántos años cumples?" },
    { "ch": "滿 48 歲。", "sp": "Cumplo cuarenta y ocho años." },
    { "ch": "你覺得我們去露營怎麼樣？", "sp": "¿Qué te parece si vamos de camping?" },
    { "ch": "我覺得很好。", "sp": "Me parece muy bien." },
    { "ch": "你叫什麼名字？你來自哪裡？", "sp": "¿Cómo te llamas? ¿Y de dónde eres?" },
    { "ch": "我叫做安東尼，我來自西班牙。", "sp": "Me llamo Antonio y soy de España." },
    { "ch": "我 22 歲。", "sp": "Tengo veintidós años." },
    { "ch": "你有幾個兄弟姊妹？", "sp": "¿Cuántos hermanos tienes?" },
    { "ch": "我有一個哥哥和一個姊姊。", "sp": "Tengo un hermano mayor y una hermana mayor." },
    { "ch": "我是最小的。", "sp": "Soy el más pequeño." },

    // 數量練習與生活應用
    { "ch": "我住在第 15 層。", "sp": "Vivo en el piso quince." },
    { "ch": "超市裡有幾串香蕉？", "sp": "¿Cuántos racimos de plátanos hay en el supermercado?" },
    { "ch": "超市裡有八串香蕉。", "sp": "Hay ocho racimos de plátanos en el supermercado." },

    // 常見單字與短語
    { "ch": "八串香蕉", "sp": "ocho racimos de plátanos" },
    { "ch": "三十一個西洋梨", "sp": "treinta y una peras" },
    { "ch": "二十八個蘋果", "sp": "veintiocho manzanas" },
    { "ch": "五個西瓜", "sp": "cinco sandías" },
    { "ch": "四十二個檸檬", "sp": "cuarenta y dos limones" },
    { "ch": "十三個鳳梨", "sp": "trece piñas" },
    { "ch": "六十四個柳橙", "sp": "sesenta y cuatro naranjas" },
    { "ch": "十七串葡萄", "sp": "diecisiete racimos de uvas" },
    { "ch": "五十九個石榴", "sp": "cincuenta y nueve granadas" }
    ],
};




