// lessons.js
const allLessons = {
    
        "第 5 課：¿Dónde está la estación? (車站在哪裡？)": [
            { ch: "不好意思，普拉多博物館在哪裡？", sp: "Perdona, ¿dónde está el museo del Prado?" },
            { ch: "離這裡有一點遠。你得搭地鐵。", sp: "Está un poco lejos de aquí. Tienes que coger el metro." },
            { ch: "地鐵站在哪裡？離這裡很近。就在書報攤對面。", sp: "¿Dónde está la estación de metro? Está cerca de aquí. Está enfrente del quiosco." },
            { ch: "非常感謝。 / 不客氣。", sp: "Muchas gracias. De nada." },
            { ch: "嗨，安東尼奧。真巧。你住在這附近嗎？", sp: "Hola, Antonio. Qué casualidad. ¿Vives cerca de aquí?" },
            { ch: "不，我在這裡是因為我和女朋友有約。", sp: "No, estoy aquí porque tengo una cita con mi novia." },
            { ch: "你現在住在哪裡？我住在合租公寓。公寓在索里亞街。", sp: "¿Dónde vives ahora? Vivo en un piso compartido. El piso está en la calle Zorrilla." },
            { ch: "我筋疲力竭，因為我有很多工作。", sp: "Estoy agotado porque tengo mucho trabajo." },
            { ch: "你來自哪裡？我來自馬德里。", sp: "¿De dónde eres tú? Yo soy de Madrid." },
            { ch: "你住在哪裡？我和朋友住在一間公寓裡。", sp: "¿Dónde vives? Vivo en un piso con mi amigo." },
            { ch: "公寓在哪裡？公寓在一家麵包店對面。", sp: "¿Dónde está el piso? El piso está enfrente de una panadería." },
            { ch: "麵包店在哪裡？它在教堂前面，廣場後面。", sp: "¿Dónde está la panadería? Está delante de la iglesia y detrás de la plaza." },
            { ch: "公寓在報攤旁邊嗎？公寓就在那裡。", sp: "¿Está el piso al lado de un quiosco? Allí está el piso." },
            { ch: "Elisa，妳丈夫在哪裡？他在法國出差。", sp: "Elisa, ¿dónde está tu marido? Está de viaje de negocios por Francia." },
            { ch: "明天他在巴黎有一個會議。", sp: "Mañana tiene una reunión en París." },
            { ch: "你們現在住在馬德里嗎？不，我們在薩拉曼卡買了一棟別墅。", sp: "¿Vivís en Madrid ahora? No, mi marido y yo compramos un chalé en Salamanca." },
            { ch: "離市中心有點遠，但在一個非常安靜的區域。", sp: "Está un poco lejos del centro, pero está en una zona muy tranquila." },
            { ch: "手機在哪裡？手機在桌子上。", sp: "¿Dónde está el móvil? El móvil está encima de la mesa." },
            { ch: "你父親在哪裡工作？我父親在一所學校工作。", sp: "¿Dónde trabaja tu padre? Mi padre trabaja en una escuela." }
        ],
        "第 6 課：Hay comedor en la facultad (學院裡有食堂)": [
            { ch: "你知道圖書館在哪裡嗎？就在影印店旁邊。", sp: "¿Sabes dónde está la biblioteca? Está ahí, al lado de la tienda de fotocopias." },
            { ch: "學院裡有食堂或咖啡廳嗎？", sp: "¿Hay un comedor o una cafetería en la facultad?" },
            { ch: "是的，這一層有一間咖啡廳和一個食堂。", sp: "Sí, hay una cafetería y un comedor en esta planta." },
            { ch: "一樓有什麼？有一些教室，秘書處也在那裡。", sp: "¿Qué hay en la primera planta? Hay unas aulas y la Secretaría está allí también." },
            { ch: "我明白了。非常感謝。", sp: "Ya veo. Muchas gracias." },
            { ch: "學院裡有多少間教室？有 10 間教室。", sp: "¿Cuántas aulas hay en la academia? Hay diez aulas en la academia." },
            { ch: "學院裡有多少學生？大約有 75 名學生。", sp: "Hay unos setenta y cinco alumnos en nuestra academia." },
            { ch: "哥雅街有一間咖啡廳。在超市旁邊。", sp: "Hay una cafetería en la calle Goya. La cafetería está al lado del supermercado." },
            { ch: "巴勃羅是一位親切的老師。", sp: "Pablo es un profesor amable." },
            { ch: "我班上大約有 30 名學生。", sp: "Hay unos treinta estudiantes in my clase." },
            { ch: "西班牙人很親切。", sp: "Los españoles son amables." },
            { ch: "狗在這裡。貓在那裡。背包在那裡（遠處）。", sp: "El perro está aquí. El gato está ahí. La mochila está allí." },
            { ch: "教室在哪裡？在走廊盡頭。", sp: "¿Dónde está el aula? Está al final del pasillo." },
            { ch: "教室裡有一塊黑板和一些桌子。有投影機嗎？", sp: "Hay una pizarra y unas mesas en el aula. ¿Hay un proyector allí?" },
            { ch: "不，沒有投影機。", sp: "No, no hay proyector." },
            { ch: "你現在住在哪裡？我住在附近的一間公寓。", sp: "¿Dónde vives ahora? Vivo en un piso por aquí cerca." },
            { ch: "我有兩個室友。我住在二樓（西班牙一樓）。", sp: "Tengo dos compañeras de piso. Vivo en la primera planta." },
            { ch: "是一間附家具的公寓嗎？是的。", sp: "¿Es un piso amueblado? Sí." }
        ],
        "第 7 課：Ellos son mis padres (他們是我的父母)": [
            { ch: "年長的是我的祖父母。他們是誰？", sp: "Los mayores son mis abuelos. ¿Quiénes son?" },
            { ch: "他們是我的父母，那邊那些是我的叔伯舅姨。", sp: "Ellos son mis padres y aquellos son mis tíos." },
            { ch: "你有兄弟姊妹嗎？有。這是我的哥哥，這是我的妹妹。", sp: "¿Tienes hermanos? Sí. Este es mi hermano mayor y esta es mi hermana menor." },
            { ch: "你好，Ana。這位是 David，我的丈夫。", sp: "Hola, Ana. Este es David, mi marido." },
            { ch: "那個男孩是妳兒子，他很高。是的，他叫 Miguel，五歲，很調皮。", sp: "Aquel chico es tu hijo. Es muy alto. Sí, se llama Miguel. Tiene cinco años y es travieso." },
            { ch: "Alberto 四歲，和妳兒子一樣調皮。但 Alberto 比 Miguel 矮。", sp: "Alberto tiene cuatro años y es tan travieso como tu hijo. Pero Alberto es más bajo que Miguel." },
            { ch: "那邊那些男孩是我的同事。那個女孩是我妹妹。", sp: "Aquellos chicos son mis compañeros. Esa chica es mi hermana menor." },
            { ch: "這是我兄弟。這是我姊妹。", sp: "Este es mi hermano. Esta es mi hermana." },
            { ch: "Felisa 比 Elisa 漂亮。José 沒有 Enrique 那麼帥。", sp: "Felisa es más guapa que Elisa. José es menos guapo que Enrique." },
            { ch: "Luisa 和 Lucía 一樣漂亮。", sp: "Luisa es tan guapa como Lucía." },
            { ch: "Felisa 說話比 Elisa 多。José 吃得比 Enrique 少。", sp: "Felisa habla más que Elisa. José come menos que Enrique." },
            { ch: "我擁有的書比 Pedro 多 / 少 / 一樣多。", sp: "Yo tengo más libros que Pedro. / Yo tengo menos libros que Pedro. / Yo tengo tantos libros como Pedro." },
            { ch: "哥哥/姊姊。弟弟/妹妹。", sp: "Hermano mayor. Hermano menor." },
            { ch: "Antonio 比我大。我比 Antonio 小。", sp: "Antonio es mayor que yo. Yo soy menor que Antonio." },
            { ch: "這幅畫比那幅好。這本書比那本差。", sp: "Este cuadro es mejor que aquel. Este libro es peor que aquel." },
            { ch: "那個高個子男人是誰？是我堂兄弟。在他右邊的是我叔叔。", sp: "¿Quién es el hombre alto? Es mi primo. A la derecha de mi primo está mi tío." },
            { ch: "那些女人是誰？", sp: "¿Quiénes son las mujeres?" },
            { ch: "那位年長的女性是我嬸嬸。她在我的堂姊妹左邊。", sp: "La mujer mayor es mi tía. Está a la izquierda de mi prima." },
            { ch: "你有幾個兄弟姊妹？", sp: "¿Cuántos hermanos tienes?" },
            { ch: "你哥哥結婚了嗎？是的，他結婚了，有一個兒子。他們住在這附近。", sp: "¿Está casado tu hermano mayor? Sí, está casado y tiene un hijo. Viven cerca de aquí." },
            { ch: "那妳妹妹呢？她單身，但有男朋友。", sp: "¿Y tu hermana menor? Está soltera, pero tiene novio." }
        ],
        "第 8 課：¿Sabes cómo llegar allí? (你知道怎麼去那裡嗎？)": [
            { ch: "這週末我們去 La Alberca 怎麼樣？那是個附近的村莊。", sp: "¿Qué tal si vamos a La Alberca este fin de semana? Es un pueblo cercano." },
            { ch: "好主意。你知道怎麼去那裡以及我們住哪裡嗎？", sp: "Buena idea. ¿Sabes cómo llegar allí y dónde nos alojamos?" },
            { ch: "我不怎麼了解那個村莊，但我們可以上網搜尋。", sp: "No conozco muy bien ese pueblo, pero podemos buscar por internet." },
            { ch: "你知道哪裡可以租車嗎？是的，我認識這附近的一家租車店。", sp: "¿Sabes dónde podemos alquilar un coche? Sí, conozco un alquiler de coches cerca de aquí." },
            { ch: "你認識那個女人嗎？是的，她是 Emilia，Enrique 的女朋友。", sp: "¿Conoces a esa woman? Sí, es Emilia, la novia de Enrique." },
            { ch: "她是台灣人，但她西班牙文和法文都說得很好。", sp: "Es taiwanesa, pero sabe muy bien español y francés." },
            { ch: "她和 Enrique 是辦公室同事。", sp: "Enrique y ella son compañeros de oficina." },
            { ch: "你知道 Enrique 有個女兒嗎？我不知道。", sp: "¿Sabes que Enrique tiene una hija? No lo sé." },
            { ch: "我不知道車站在哪裡。", sp: "No sé dónde está la estación." },
            { ch: "你知道怎麼使用這台相機嗎？抱歉，我不知道。", sp: "¿Sabes cómo usar la cámara? Lo siento, no lo sé." },
            { ch: "Alicia 的西班牙文非常好。Elisa 一點都不懂。", sp: "Alicia sabe muy bien español. Elisa no sabe nada de español." },
            { ch: "María 非常了解台南。你認識 Emilia 嗎？", sp: "María conoce muy bien Tainan. ¿Conoces a Emilia?" },
            { ch: "我不能唱歌，因為我感冒了。", sp: "No puedo cantar porque estoy resfriado." },
            { ch: "你可以來機場接我嗎？", sp: "¿Puedes recogerme en el aeropuerto?" },
            { ch: "我兄弟會踢足球。", sp: "Mi hermano sabe jugar al fútbol." },
            { ch: "你對這個村莊熟悉嗎？有一點。", sp: "¿Conoces bien este pueblo? Un poco." },
            { ch: "你知道哪裡可以野餐嗎？我認識這附近的一個公園。", sp: "¿Sabes dónde puedo hacer picnic? Conozco un parque cerca de aquí." },
            { ch: "那哪裡可以喝咖啡？我不知道，但我們可以上網找。", sp: "¿Y dónde puedo tomar café? No lo sé, pero podemos buscar por internet." },
            { ch: "和 Eva 及 Enrique 一起去露營怎麼樣？好主意。", sp: "¿Qué tal si vamos de camping con Eva y Enrique? Buena idea." },
            { ch: "我們可以在那裡烤肉和做西班牙大鍋飯。", sp: "Podemos hacer barbacoa y paella allí." },
            { ch: "你會做大鍋飯嗎？當然。此外，我還要做水果酒和開胃菜。", sp: "¿Sabes cómo hacer paella? Por supuesto. Además, voy a hacer sangría y tapas." }
        ] 

};
